blank_issues_enabled: false
contact_links:
  - name: Report a security problem
    url: https://github.com/JWU-NCSA/.github/blob/main/SECURITY.md
    about: Do not open a public issue for security problems. Follow the security policy.
